#!/usr/bin/env python3
"""
tools/makefsdata.py
Converts web assets in a directory into lwIP httpd-compatible C source code (fsdata.c).
"""

import sys
import os

FS_FILE_FLAGS_HEADER_INCLUDED = 0x01
FS_FILE_FLAGS_SSI             = 0x02

MIME_TYPES = {
    '.html': 'text/html',
    '.shtml': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
    '.svg': 'image/svg+xml',
    '.txt': 'text/plain'
}

def generate_http_header(mime, content_length):
    return (
        f"HTTP/1.1 200 OK\r\n"
        f"Server: STM32H723-lwIP\r\n"
        f"Content-Type: {mime}\r\n"
        f"Content-Length: {content_length}\r\n"
        f"Connection: close\r\n"
        f"\r\n"
    ).encode('utf-8')

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <web_folder> <output_fsdata.c>")
        sys.exit(1)

    web_dir = sys.argv[1]
    out_file = sys.argv[2]

    files_data = []
    
    # Traverse web directory
    for root, _, files in os.walk(web_dir):
        for f in sorted(files):
            if f.startswith('.'):
                continue
            full_path = os.path.join(root, f)
            rel_path = os.path.relpath(full_path, web_dir)
            web_path = '/' + rel_path.replace('\\', '/')

            with open(full_path, 'rb') as fp:
                body = fp.read()

            ext = os.path.splitext(f)[1].lower()
            mime = MIME_TYPES.get(ext, 'application/octet-stream')
            is_ssi = (ext == '.shtml')

            # Build full HTTP payload (headers + body)
            header = generate_http_header(mime, len(body))
            full_payload = header + body

            flags = FS_FILE_FLAGS_HEADER_INCLUDED
            if is_ssi:
                flags |= FS_FILE_FLAGS_SSI

            files_data.append({
                'web_path': web_path,
                'var_name': 'data_' + rel_path.replace('/', '_').replace('.', '_').replace('-', '_'),
                'file_name_var': 'name_' + rel_path.replace('/', '_').replace('.', '_').replace('-', '_'),
                'payload': full_payload,
                'flags': flags
            })

    # Also add / to point to /index.shtml
    for fd in files_data:
        if fd['web_path'] == '/index.shtml':
            files_data.append({
                'web_path': '/',
                'var_name': fd['var_name'],
                'file_name_var': 'name_root',
                'payload': None, # reuse data
                'flags': fd['flags'],
                'alias_of': fd
            })
            break

    # Generate C output
    with open(out_file, 'w', encoding='utf-8') as out:
        out.write("/* Auto-generated by tools/makefsdata.py. Do not edit manually. */\n\n")
        out.write("#include \"lwip/apps/fs.h\"\n")
        out.write("#include \"lwip/def.h\"\n")
        out.write("#include \"lwip/apps/httpd_opts.h\"\n\n")

        # Emit byte arrays for payloads
        for fd in files_data:
            if fd.get('alias_of'):
                continue
            payload = fd['payload']
            var_name = fd['var_name']
            out.write(f"static const unsigned char {var_name}[] = {{\n")
            # Write bytes in chunks of 16
            for i in range(0, len(payload), 16):
                chunk = payload[i:i+16]
                hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
                out.write(f"    {hex_str},\n")
            out.write("};\n\n")

        # Emit file name strings
        for fd in files_data:
            name_bytes = fd['web_path'].encode('utf-8') + b'\x00'
            var_name = fd['file_name_var']
            hex_str = ", ".join(f"0x{b:02x}" for b in name_bytes)
            out.write(f"static const unsigned char {var_name}[] = {{ {hex_str} }};\n")
        out.write("\n")

        # Emit linked list of fsdata_file structures
        # In lwIP, the last file has next = NULL, each preceding points to the next
        out.write("/* Linked list of embedded files */\n")
        prev_struct_name = "NULL"
        for i in reversed(range(len(files_data))):
            fd = files_data[i]
            struct_name = f"file_{i}"
            data_var = fd['alias_of']['var_name'] if fd.get('alias_of') else fd['var_name']
            data_len = len(fd['alias_of']['payload']) if fd.get('alias_of') else len(fd['payload'])
            name_var = fd['file_name_var']
            flags = fd['flags']

            out.write(f"const struct fsdata_file {struct_name} = {{\n")
            out.write(f"    {prev_struct_name},\n")
            out.write(f"    {name_var},\n")
            out.write(f"    {data_var},\n")
            out.write(f"    {data_len},\n")
            out.write(f"    {flags}\n")
            out.write("};\n\n")
            prev_struct_name = f"&{struct_name}"

        # Root definition
        out.write(f"#define FS_ROOT {prev_struct_name}\n")
        out.write(f"#define FS_NUMFILES {len(files_data)}\n")

    print(f"Generated {out_file} with {len(files_data)} file entries successfully.")

if __name__ == '__main__':
    main()
